name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "23f3002264@ds.study.iitm.ac.in"
        run: echo "This step is being checked by the grader!"

      - name: "A second step"
        run: echo "Hello, world!"
